version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: ProcurementMaterialAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=Materuals;User=sa;Password=Passw0rd;TrustServerCertificate=True;
    ports:
      - "8080:8080"
    depends_on:
      - mssql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
